# example netlify.toml
[build]
  command = "npm run build"
  functions = "functions"
  publish = "public"

  ## Uncomment to use this redirect for Single Page Applications like create-react-app. 
  ## Not needed for static site generators.
  #[[redirects]]
  #  from = "/*"
  #  to = "/index.html"
  #  status = 200
  
  # (optional) Settings for Netlify Dev
  # https://github.com/netlify/netlify-dev-plugin#project-detection
[dev] 
  command = "npm run netlify:dev" # Command to start your dev server
  port = 8000 # Port that the dev server will be listening on
  functions = "functions"
  publish = "public"
  
  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/ 
